server:
  port: 8989
  context-path: /spring_day02
  jsp-servlet:
    init-parameters:
      development: true
spring:
  datasource:
    name: qp
    url: jdbc:mysql://localhost:3306/qp
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  http:
    encoding:
      charset: utf-8
      force: true
    multipart:
      max-request-size: 100Mb
      max-file-size: 10Mb
  mvc:
    view:
      prefix: /
      suffix: .jsp

mybatis:
  type-aliases-package: com.doudou.entity
  mapper-locations: classpath:com/doudou/dao/*Dao.xml
